config/routes.rb
ProjectApp::Application.routes.draw do 

  resources :wishes

	resources :authorizations

  match '/auth/:provider/callback' => 'authorizations#create', via: [:get]

  resources :carts

  resources :contributors

  resources :event_products 

  resources :comments

  resources :events

  resources :posts 

  #faye_server '/faye', timeout: 25
  #get '/chat', to: RealtimeChatController

  resources :products

  resources :categories
  
  #get '/categories' => 'categories#new'
  #get 'add_event' => 'events#new', :as => :add_event
  #get '/events' => 'events#new'	, :as => :event_new 
  #get '/contributors' => 'contributors#new' 
  get '/friend' => 'friend/users#index', :as => :friend
  #get 'latest_products' => 'products#index', :as => :latest_products
 
  namespace :friend do
    resources :users 
  end  

  namespace :admin do
    resources :users, :settings, :footer_pages, :contacts, :languages, :email_templates
  end
  
  resources :event_products do
    resources :comments
  end

  resources :event_products do
    resources :contributors
  end

 resources :events do
    resources :event_products
  end
	
	 get '/userFunds/:id/:given_price' => 'contributors#userfund', :as => :fundfromfriend

   get 'events/filter/:status' => 'events#index', :as => :filter_event_status

   get '/products' => 'products#new'

   get '/contributors/my/:user_id' => 'contributors#index', :as => :contribution_by_me	

   get '/contributors/friend/:user_contribute_id' => 'contributors#index', :as => :contribution_by_friend

  

  resources :user_sessions
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup(/:registration_key)' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]

  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
 # get 'dashboard' => 'fronts#dashboard', :as => :dashboard
   get 'dashboard' => 'events#index', :as => :dashboard
  match 'activate/:activation_key' => 'fronts#user_activation', :as => :activation_link, via: [:get]

  #match 'event_product/:event_product_id' => 'fronts#user_event_product', :as => :event_product_link, via: [:get, :post]

  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box
  #get '/my_account' => 'fronts#my_account', :as => :my_account
	#match '/profile' => 'fronts#profile', :as => :my_account, via: [:get, :post, :patch]
  get '/about_us' => 'fronts#about_us', :as => :about_us
  get '/privacy_policy' => 'fronts#privacy_policy', :as => :privacy_policy
  get'/terms_and_condition' => 'fronts#terms_and_condition', :as => :terms_and_condition
  match '/contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other

  

  # You can have the root of your site routed with "root"
 # root 'fronts#dashboard'
	root 'events#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	mount_uploader :image, ImageUploader

	belongs_to :user
	belongs_to :event_product

	def get_user_name(id)
		@uname = User.find(id)
		@uname.first_name
	end

	def get_user_image(id1)
		@user_image = User.find(id1)
		@user_image.image
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    #@comment = @event_product.Comment.build
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json

  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.event_product_id = session[:event_product_id]
    @event_product = EventProduct.find(session[:event_product_id])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
       # format.json { render action: 'show', status: :created, location: @comment }
	format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
	@event_product = EventProduct.find(session[:event_product_id])
     @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      #format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :event_product_id, :description, :image)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @event_product.comments.each do |comment| %>
<p>
   <table>
	<tr>

    	   <td align=left>&nbsp&nbsp<strong><b style="color:blue;text-align:left"><%= comment.get_user_name(comment.user_id) %> </b> </strong><br /></td>
<tr>

<td align=left>&nbsp&nbsp<strong><%=image_tag (comment.get_user_image(comment.user_id)),:width => 50, :height => 50  %>  </strong><br /></td>

	   <td align=left>&nbsp&nbsp<%= h(comment.description) %></td>
	   
	   <td align=left>&nbsp&nbsp<strong>Posted <%= time_ago_in_words(comment.created_at) %></strong></br></td>
	   
	   <% if comment.user_id == current_user.id %>
	   <td align=left>&nbsp&nbsp<%= link_to 'Destroy', comment, method: :delete, :remote => true %></td>
	   <% end %>
</tr>

	  </tr>
    </table>
</p>
<% end %>
<td> <b style="color:green;text-align:left"><%= pluralize @event_product.comments.size, "comment" %> </b> </td>	

app/views/comments/_form.html.erb
<%= form_for (@comment) do |f|  %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<br><br>
<!--  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :event_product_id %><br>
    <%= f.number_field :event_product_id %>
  </div>--!>

  <div class="field">
    <%= f.label :Leave_a_Comment %><br>
    <%= f.text_area :description %>
  </div>

  <div class="control-group">
        <%= f.label :User_Image, :class => 'control-label' %>
        <div class="controls">
            <%= f.file_field :image, :class => 'input-xlarge' %>
        </div>
  </div>
  <% if @comment.image? %>
        <div class="control-group"><div class="controls"><%= image_tag @comment.image_url(:logo) %></div></div>
  <% end %>
<br><br>
    <%= f.submit %>
  </div>
<br>
<% end %>

app/views/comments/create.js.erb
/* Add the new comment to the bottom of the comments list */
$("#comments").html("<%= escape_javascript(render("comment")) %>");

/* Reset the comment form */
$("#new_comment")[0].reset();

app/views/comments/destroy.js.erb
/* Destroy the comment  of the comments list */
$("#comments").html("<%= escape_javascript(render("comment")) %>");

/* Reset the comment form */
$("#destroy_comm")[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<html>
<h4 style="color:#336699;text-align:left"> Comments </h4>
<hr>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event product</th>
      <th>Description</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.get_user_name(comment.user_id) %></td>
        <td><%= comment.event_product_id %></td>
        <td><%= comment.description %></td>
	<td><%= image_tag comment.get_user_image(comment.user_id), :size => "50x50" %></td>
        <!--<td><%= comment.image %></td>
	<td><%= image_tag comment.image_url(:logo) %>-->
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Comment', new_comment_path %>!-->

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
<%= link_to 'Back', event_products_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.get_user_name(@comment.user_id) %>
</p>

<p>
  <strong>Event product:</strong>
  <%= @comment.event_product_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @comment.image_url(:logo) %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', event_products_path %>