config/routes.rb
ProjectApp::Application.routes.draw do 

  resources :wishes

	resources :authorizations

  match '/auth/:provider/callback' => 'authorizations#create', via: [:get]

  resources :carts

  resources :contributors

  resources :event_products 

  resources :comments

  resources :events

  resources :posts 

  #faye_server '/faye', timeout: 25
  #get '/chat', to: RealtimeChatController

  resources :products

  resources :categories
  
  #get '/categories' => 'categories#new'
  #get 'add_event' => 'events#new', :as => :add_event
  #get '/events' => 'events#new'	, :as => :event_new 
  #get '/contributors' => 'contributors#new' 
  get '/friend' => 'friend/users#index', :as => :friend
  #get 'latest_products' => 'products#index', :as => :latest_products
 
  namespace :friend do
    resources :users 
  end  

  namespace :admin do
    resources :users, :settings, :footer_pages, :contacts, :languages, :email_templates
  end
  
  resources :event_products do
    resources :comments
  end

  resources :event_products do
    resources :contributors
  end

 resources :events do
    resources :event_products
  end
	
	 get '/userFunds/:id/:given_price' => 'contributors#userfund', :as => :fundfromfriend

   get 'events/filter/:status' => 'events#index', :as => :filter_event_status

   get '/products' => 'products#new'

   get '/contributors/my/:user_id' => 'contributors#index', :as => :contribution_by_me	

   get '/contributors/friend/:user_contribute_id' => 'contributors#index', :as => :contribution_by_friend

  

  resources :user_sessions
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup(/:registration_key)' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]

  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
 # get 'dashboard' => 'fronts#dashboard', :as => :dashboard
   get 'dashboard' => 'events#index', :as => :dashboard
  match 'activate/:activation_key' => 'fronts#user_activation', :as => :activation_link, via: [:get]

  #match 'event_product/:event_product_id' => 'fronts#user_event_product', :as => :event_product_link, via: [:get, :post]

  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box
  #get '/my_account' => 'fronts#my_account', :as => :my_account
	#match '/profile' => 'fronts#profile', :as => :my_account, via: [:get, :post, :patch]
  get '/about_us' => 'fronts#about_us', :as => :about_us
  get '/privacy_policy' => 'fronts#privacy_policy', :as => :privacy_policy
  get'/terms_and_condition' => 'fronts#terms_and_condition', :as => :terms_and_condition
  match '/contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other

  

  # You can have the root of your site routed with "root"
 # root 'fronts#dashboard'
	root 'events#index'

end

app/models/category.rb
class Category < ActiveRecord::Base

	#require "product.rb"

	has_many :products
	#validates :category_id, :presence => true
	validates :name, :presence => true
	validates :description, :presence => true

  def self.search(search)
  		if search
    			find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  		else
    			find(:all)
  		end
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  #require 'category.rb'
  
  # GET /categories
  # GET /categories.json
  def index
   
    @categories = Category.all
    @product = Product.new
	
    # @categories= Category.paginate(:page => params[:page], :per_page => 3)
     @categories = Category.all.search(params[:search]).paginate(:page => params[:page], :per_page => 3)
    ##categories = Category.search(params[:search])
    #@categories = Category.includes(:products).search(params[:search])	
	
    #@categories = Category.joins(:product)
   
    #@categoris do |category|
	#category.product
    #end

    #@categories = Category.joinTables
	
  end


  # GET /categories/1
  # GET /categories/1.json
  def show
		
  end

  # GET /categories/new
  def new
    @category = Category.new
    @product = Product.new
    
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
		@categories= Category.paginate(:page => params[:page], :per_page => 3)
    @category = Category.new(category_params)
    
    respond_to do |format|
	
  	 if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
		@categories= Category.paginate(:page => params[:page], :per_page => 3)
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      #format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_id, :name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_fetchAll.html.erb
<h4 style="color:#336699;text-align:center"><b>SELECT PRODUCTS</b> </h4>
<hr>
<%= form_tag categories_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] , :class => 'input-xlarge' %> &nbsp;
    <%= submit_tag "Search", :name => nil , :class => 'btn btn-primary'%>
  </p>

<% end %>

<table>
   <!--<thead>
    <tr>
     <th align=left><h2><i>Category</h2></i></th>
     <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th> 
    </tr>
  </thead> -->

  <hr /> 

  <tbody>
   	<div id="temp">
				<% if is_admin? %>
					<b><%= link_to "Add New Category",new_category_path, id: "new_category_link", remote: true  %> </b> |
  				<b><%= link_to "Add New Product",new_product_path, id: "new_product_link", remote: true %> </b> 
  				<hr />
    		<% end %>	

   		<% @categories.each do |category| %>
				<div class="col-sm-12">   
					<% if is_admin? %>
						<b><%= link_to 'Destroy Category', category, method: :delete, remote: true %></b>
					<% end %>	
					<h4>
					<b style="color:blue;text-align:left"><%=link_to category.name,category %> (<%= pluralize category.products.size, "product" %>)
					</b>
					</h4>

					<%- category_product = category.products.each_slice(3).to_a %>
					<div class="col-sm-12">
						<div data-ride="carousel" class='carousel slide' id="carousel_<%= category.id %>">
							<div class="carousel-inner">
								<% category_product.each_with_index do |product_list, index| %>
					
									<div class="item <%= 'active' if index == 0 %>">
										<% product_list.each do |product| %>
											<div class="col-sm-4 col-lg-4 col-md-4">
												<div class="thumbnail">
														<div style="padding:4px">
															<%= link_to (image_tag product.image_one_url, :size => "50x50"), product %>
															<br />
															
															<div class="caption">
																<ul>
																	<h5>
																		<b style="color:#336699;">Product Name: </b>
																		<%= link_to product.product_name, product, :style=>'color:#336699' %>
																	</h5>
							
																	<h5><b style="color:#336699;">Price: </b><%= product.price %></h5>	
																	<h5><b style="color:#336699;">Description: </b><%= product.description %></h5>
																</ul>
															</div> <!--caption-->
															
															<hr />
															<div class="separator clear-left">
																<p class="pull-left">
																	<!--<i class="fa fa-shopping-cart"></i><%= link_to "Add To Cart",new_cart_path(product) %>-->
																</p>

																<p class="pull-right">
																	<i class="fa fa-list"></i><%= link_to "More details", product %></p>
															</div> <!--separator clear-left-->
																			
															<div class="clearfix">
															</div>
														</div>
												</div>
											</div>
										<% end %>
									</div>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
  </tbody>
</table>
<br>
<%= will_paginate @categories, :previous_label => 'Previous', :next_label => 'Next' %>

app/views/categories/_fetchCategory.html.erb
<% @categories.each do |category| %>

	<li> <h6 style="color:#336699"><%=link_to category.name, category %><em>(<%= pluralize category.products.size,"" %>)</em> </h6> </li>
     <!-- <% category.products.each do |product| %>
	      <%= link_to product.product_name, product, :style=>'color:#336699' %>
      <% end %> -->
<% end %>

app/views/categories/_fetchProduct.html.erb
<% @categories.each do |category| %>

	<b><%=link_to category.name, category %> (<%= pluralize category.products.size, "" %>)</b><br>
     
<% end %>

app/views/categories/_form.html.erb
<%= form_for @category, remote:true do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id, :placeholder => 'Category Id'%>
  </div>!-->


<div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'input-xlarge' %>
      </div>
    </div>

<div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, :class => 'input-xlarge' %>
      </div>
    </div>
<%= link_to 'Back', categories_path %>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/categories/create.js.erb
$("#categories").html("<%= escape_javascript(render("fetchAll")) %>");

app/views/categories/destroy.js.erb
$("#categories").html("<%= escape_javascript(render("fetchAll")) %>");

app/views/categories/edit.html.erb
<h4 style="color:#336699;text-align:center">EDIT CATEGORIES </h4>
<hr>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div id="categories">
<%= render 'fetchAll' %>
</div>

app/views/categories/index.js.erb
$("#categories").html("<%= escape_javascript(render("fetchAll")) %>");

app/views/categories/new.html.erb
<!--<h4 style="color:#336699;text-align:center"> ADD NEW CATEGORIES </h4>
<hr>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>-->

app/views/categories/new.js.erb
$('#new_category_link').hide().after('<%= j render("form")%>');

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

 <% @category.products.each do |product| %>
        
            <div class="col-sm-4 col-lg-4 col-md-4">
			<div class="thumbnail">	
				<div style="padding:4px">
              		<!--<img alt="300x200" style="width: 100%" src="http://placehold.it/200x150">-->
						<%= link_to (image_tag product.image_one_url, :size => "50x50"), product %>
            	</div>
				<div class="caption">
					<ul>
						<h5><b style="color:#336699;">Product Name: </b><%= link_to product.product_name, product, :style=>'color:#336699' %></h5>
						
	  						<h5><b style="color:#336699;">Price: </b><%= product.price %></h5>	

		   				<h5><b style="color:#336699;">Description: </b><%= product.description %></h5>
					</ul>
				</div>

					<hr />
														<div class="separator clear-left">
                  						<p class="pull-left">
                  							<!--<i class="fa fa-shopping-cart"></i><%= link_to "Add To Cart",new_cart_path(product) %>-->
															</p>

                  						<p class="pull-right">
                  							<i class="fa fa-list"></i><%= link_to "More details", product %></p>
            								</div> <!--separator clear-left-->
                                   
				 										<div class="clearfix">
                 						</div>
			
             </div>
</div>

      <% end %>

<!-- <%= link_to 'Back', categories_path %> -->
</div>