config/routes.rb
ProjectApp::Application.routes.draw do 

  resources :wishes

	resources :authorizations

  match '/auth/:provider/callback' => 'authorizations#create', via: [:get]

  resources :carts

  resources :contributors

  resources :event_products 

  resources :comments

  resources :events

  resources :posts 

  #faye_server '/faye', timeout: 25
  #get '/chat', to: RealtimeChatController

  resources :products

  resources :categories
  
  #get '/categories' => 'categories#new'
  #get 'add_event' => 'events#new', :as => :add_event
  #get '/events' => 'events#new'	, :as => :event_new 
  #get '/contributors' => 'contributors#new' 
  get '/friend' => 'friend/users#index', :as => :friend
  #get 'latest_products' => 'products#index', :as => :latest_products
 
  namespace :friend do
    resources :users 
  end  

  namespace :admin do
    resources :users, :settings, :footer_pages, :contacts, :languages, :email_templates
  end
  
  resources :event_products do
    resources :comments
  end

  resources :event_products do
    resources :contributors
  end

 resources :events do
    resources :event_products
  end
	
	 get '/userFunds/:id/:given_price' => 'contributors#userfund', :as => :fundfromfriend

   get 'events/filter/:status' => 'events#index', :as => :filter_event_status

   get '/products' => 'products#new'

   get '/contributors/my/:user_id' => 'contributors#index', :as => :contribution_by_me	

   get '/contributors/friend/:user_contribute_id' => 'contributors#index', :as => :contribution_by_friend

  

  resources :user_sessions
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup(/:registration_key)' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]

  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
 # get 'dashboard' => 'fronts#dashboard', :as => :dashboard
   get 'dashboard' => 'events#index', :as => :dashboard
  match 'activate/:activation_key' => 'fronts#user_activation', :as => :activation_link, via: [:get]

  #match 'event_product/:event_product_id' => 'fronts#user_event_product', :as => :event_product_link, via: [:get, :post]

  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box
  #get '/my_account' => 'fronts#my_account', :as => :my_account
	#match '/profile' => 'fronts#profile', :as => :my_account, via: [:get, :post, :patch]
  get '/about_us' => 'fronts#about_us', :as => :about_us
  get '/privacy_policy' => 'fronts#privacy_policy', :as => :privacy_policy
  get'/terms_and_condition' => 'fronts#terms_and_condition', :as => :terms_and_condition
  match '/contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other

  

  # You can have the root of your site routed with "root"
 # root 'fronts#dashboard'
	root 'events#index'

end

app/models/product.rb
class Product < ActiveRecord::Base

	belongs_to :category
	has_many :event_products
  has_many :carts
	has_many :wishes
	validates :product_name, :presence => true
	validates :description, :presence => true
	validates :price, :presence => true

	mount_uploader :image_one, ImageUploader

	def get_category_name(id)
		@nm = Category.find(id)
		@nm.name
	end

	def get_price(id)
		@value = Product.find(id)
		@value.price
	end	

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  
  # GET /products
  # GET /products.json

  #@products = Products.includes(:categories)

  def index
    
    #@product = products.joins([:categories])
    #@products = (Product.all).joins(:categories)
    #@product = Product.find(:all, :include => :categories)

    #@products = Product.find(:all, :order => "category_id asc")
    #@products = Product.find(:all, :order => "created_at desc").paginate(:page => params[:page], :per_page => 2)
  	session[:product_id] = params[:id] 
    @products = Product.where("created_at >= ?", 7.days.ago).paginate(:page => params[:page], :per_page => 2)

  end

  # GET /products/1
  # GET /products/1.json

  def show
	#  
     session[:product_id] = params[:id]     
     @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
    #
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
	#
	@product = Product.find(params[:id])
	@categories = Category.all
  end

  # POST /products
  # POST /products.json

  def create
    @product = Product.new(product_params)
   
    respond_to do |format|
      if @product.save	
	#@product = Product.new(:product_name => params[:products][:product_name],
	#:category_id => params[:products][:category_id])  
        format.html { redirect_to categories_url, notice: 'Product was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @product }
				format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:category_id, :product_name, :description, :image_one, :price)
    end
  
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product, remote:true, :authenticity_token => true do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
	<!-- <lable for="product_category_id">Category</label><br> !-->
<%= select("product","category_id",Category.find(:all).collect {|c| [c.name,c.id] } ,{:include_blank => '----- Select Category -------' }) %></p>
  </div>



<div class="control-group">
      <%= f.label :product_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :product_name, :class => 'input-xlarge' %>
      </div>
    </div>

<div class="control-group">
      <%= f.label :description, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :description, :class => 'input-xlarge' %>
      </div>
    </div>


   <div class="control-group">
        <%= f.label :image, :class => 'control-label' %>
        <div class="controls">
            <%= f.file_field :image_one, :class => 'input-xlarge' %>
        </div>
    </div>
    <% if @product.image_one? %>
        <div class="control-group"><div class="controls"><%= image_tag @product.image_one_url(:logo) , :size => "260x180"  %></div></div>
    <% end %>

<div class="control-group">
      <%= f.label :price, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :price, :class => 'input-xlarge' %>
      </div>
    </div>

<%= link_to 'Back', categories_path %>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/create.js.erb
$("#create_product").html("<%= escape_javascript(render("form")) %>");

app/views/products/edit.html.erb
<h4 style="color:#336699;text-align:center">EDIT PRODUCTS </h4>
<hr>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<!--<%= link_to 'Back', products_path %>!-->

<%= link_to 'Back', categories_path %>

app/views/products/index.html.erb
<h4 style="color:#336699;text-align:center">PRODUCTS </h4>
<hr>

<table>
 <!-- <thead>
    <tr>
      <th>Category</th>
      <th></th>
      <th>Product name</th>
      <th>Description</th>

      <th>Image one</th>
      <th>Price</th> 

      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
!-->

  <tbody>
	<!-- <td><h4><b style="color:blue;text-align:left"> Category </b></h4></td> 
       <td> </td>
        <td><h4><b style="color:blue;text-align:left"> Product Name</b></h4></td> !-->
	

    <% @products.each do |product| %>
      <tr>
       <!--  <td> <b style="color:green;text-align:left"><%= (product.get_category_name(product.category_id)) %> </b></td> !-->
	<td></td>
        <td> <h4 style="color:green;text-align:left"><%=link_to(product.product_name,product) %></h4></td>

		<!--<% product.event_products.each do |event_product| %>
		<tr>	
		   <td> 	<%= link_to (event_product.get_event_name(event_product.event_id)), event_product %></td>
		   <td><%= link_to (event_product.get_product_name(event_product.product_id)), event_product %></td>
	   
		</tr>
    		<% end %>!-->

	<td> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= image_tag product.image_one_url(:logo) , :size => "50x50" %></td>

        <!--<td><%= product.description %></td>
        <td><%= product.image_one %></td>
        <td><%= product.price %></td>-->
        <!--<td><%= link_to 'Show', product %></td>-->
        <!--<td><%= link_to 'Edit', edit_product_path(product) %></td>-->
        <!--<td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @products, :previous_label => 'Previous', :next_label => 'Next' %>
<!-- <%= link_to 'New Product', new_product_path %> !-->
</div>

app/views/products/new.html.erb
<h4 style="color:#336699;text-align:center"> ADD NEW PRODUCTS </h4>
<hr>

<div id="create_product">
<%= render 'form' %>
</div>

<!--<%= link_to 'Back', products_path %>!-->

<%= link_to 'Back', categories_path %>

app/views/products/new.js.erb
$('#new_product_link').hide().after('<%= j render("form")%>');

app/views/products/show.html.erb
<div class="row">
	<div class="col-md-5">
		<br><br><br>
  	 	<%= image_tag @product.image_one_url, :size => "300x400" %>
				<br><br><br>
					<% if is_admin? %>
						<%= link_to 'Edit', edit_product_path(@product) %> |
						<%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %> |
					<% end %>
			<%= button_to 'Back', categories_path, :class => "btn btn-primary", :method => :get  %>
			<!--<%= link_to 'Back', products_path %>!-->
	</div>
	
<div class="product-info">
	<div class="col-md-6">
		<div id="product">
			<h3 style="color:#336699;text-align:left;font-weight:bold"> <%= @product.product_name.capitalize %></h3>
			
			<hr />
				
				<div class="description">
				<ul>
					<li><span style="color:#336699;text-align:left;font-weight:bold">Details: &nbsp </span> <%= @product.description %></li>
					<br>
					<li><span style="color:#336699;text-align:left;font-weight:bold">Availability: &nbsp </span> In Stock</li>
					<br>
					<li><span style="color:#336699;text-align:left;font-weight:bold">Price: &nbsp</b></span><%= @product.price %></li>
					<br>
				</ul>
				</div>

					<hr>
				<form class="form-inline">

			<!--	<%= button_to 'Add to Cart', new_cart_path(product_id: @product ) %> -->
                   <%= image_tag "cart.png" %> <%= link_to "Add To Cart",new_cart_path(@product.id) %>  
                   <!-- <%= link_to "Add To Wishlist",new_wish_path(@product.id) %>  -->   
                     <br>     
                    </form>
				</div>
			</div>
		</div>
	
	</div>		

</div>