config/routes.rb
ProjectApp::Application.routes.draw do 

  resources :wishes

	resources :authorizations

  match '/auth/:provider/callback' => 'authorizations#create', via: [:get]

  resources :carts

  resources :contributors

  resources :event_products 

  resources :comments

  resources :events

  resources :posts 

  #faye_server '/faye', timeout: 25
  #get '/chat', to: RealtimeChatController

  resources :products

  resources :categories
  
  #get '/categories' => 'categories#new'
  #get 'add_event' => 'events#new', :as => :add_event
  #get '/events' => 'events#new'	, :as => :event_new 
  #get '/contributors' => 'contributors#new' 
  get '/friend' => 'friend/users#index', :as => :friend
  #get 'latest_products' => 'products#index', :as => :latest_products
 
  namespace :friend do
    resources :users 
  end  

  namespace :admin do
    resources :users, :settings, :footer_pages, :contacts, :languages, :email_templates
  end
  
  resources :event_products do
    resources :comments
  end

  resources :event_products do
    resources :contributors
  end

 resources :events do
    resources :event_products
  end
	
	 get '/userFunds/:id/:given_price' => 'contributors#userfund', :as => :fundfromfriend

   get 'events/filter/:status' => 'events#index', :as => :filter_event_status

   get '/products' => 'products#new'

   get '/contributors/my/:user_id' => 'contributors#index', :as => :contribution_by_me	

   get '/contributors/friend/:user_contribute_id' => 'contributors#index', :as => :contribution_by_friend

  

  resources :user_sessions
  get 'logout' => 'user_sessions#destroy', :as => :logout
  get 'login' => 'user_sessions#new', :as => :login
  match 'signup(/:registration_key)' => 'user_sessions#signup', :as => :signup, via: [:get, :post, :patch]

  match '/forgot_password' => 'fronts#forgot_password', :as => :forgot_password, via: [:get, :post]
  match '/change_password' => 'fronts#change_password', :as => :change_password, via: [:get, :post, :patch]
 # get 'dashboard' => 'fronts#dashboard', :as => :dashboard
   get 'dashboard' => 'events#index', :as => :dashboard
  match 'activate/:activation_key' => 'fronts#user_activation', :as => :activation_link, via: [:get]

  #match 'event_product/:event_product_id' => 'fronts#user_event_product', :as => :event_product_link, via: [:get, :post]

  match '/profile' => 'fronts#profile', :as => :profile, via: [:get, :post, :patch]
  get '/show_search_box/:toggle/:model/:pm' => 'fronts#show_search_box', :as => :show_search_box
  #get '/my_account' => 'fronts#my_account', :as => :my_account
	#match '/profile' => 'fronts#profile', :as => :my_account, via: [:get, :post, :patch]
  get '/about_us' => 'fronts#about_us', :as => :about_us
  get '/privacy_policy' => 'fronts#privacy_policy', :as => :privacy_policy
  get'/terms_and_condition' => 'fronts#terms_and_condition', :as => :terms_and_condition
  match '/contact_us' => 'fronts#contact_us', :as => :contact_us, via: [:get, :post, :patch]
  get '/other/:page_id' => 'fronts#other', :as => :other

  

  # You can have the root of your site routed with "root"
 # root 'fronts#dashboard'
	root 'events#index'

end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
	belongs_to :user
	belongs_to :event_product
	has_many :contributed, class_name: 'Contributor', foreign_key: "user_contribute_id", dependent: :destroy


	validates_numericality_of :given_price, :greater_than_or_equal_to => 10
  

	def get_user_name(id)
	   @uname = User.find(id)
	   @uname.first_name
	end

	def get_total_contribution(id)
		@value = Contributor.where(event_product_id: id).group(:event_product_id).sum(:given_price)
		Hash h = @value
	end

	def get_contribution_id(id)
		@id = EventProduct.find(id)
		@id.event_id
	end

	def get_user_id(id)
		@uid = Event.find(id)
		@uid.user_id
  end

	def get_product_id(id)
		@pid = EventProduct.find(id)
		@pid.product_id
	end

	def get_product_image(id)
		@img= Product.find(id)
		@img.image_one
	end
	
	def get_product_name(id)
		@pname = Product.find(id)
		@pname.product_name
	end	

	def get_event_id(id)
		@name = EventProduct.find(id)
		@name.event_id
	end

	def get_event_name(id)
		@name = Event.find(id)
		@name.event_name
	end

	
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  before_action :set_contributor, only: [:show, :edit, :update, :destroy]

  # GET /contributors
  # GET /contributors.json
  def index
    if user_is_logged_in?
   # @event_product = EventProduct.new
	@contributor = Contributor.find(:all, :conditions => ["user_id = ?", current_user.id] ).paginate(:page => params[:page], :per_page => 3)

	@contribute_me = params[:user_id]
	@contribute_friend = params[:user_contribute_id]

	if @contribute_me == 'my'
		@contributor = Contributor.find(:all, :conditions => ["user_id = ?", current_user.id] ).paginate(:page => params[:page], :per_page => 3)
		elsif @contribute_friend == 'friend'
			@contributor = Contributor.find(:all, :conditions => ["user_contribute_id = ?", current_user.id] ).paginate(:page => params[:page], :per_page => 3)
		else
			
		end

    else
	respond_to do |format|
	format.html { redirect_to login_url, notice: "First Login...!!!" }
        format.json { head :no_content }
        end    
    end
  end

  # GET /contributors/1
  # GET /contributors/1.json
  def show
	#@event_product = EventProduct.find(params[:id])
  end

  # GET /contributors/new
  def new
    @contributor = Contributor.new
  end

  # GET /contributors/1/edit
  def edit
  end

  # POST /contributors
  # POST /contributors.json
  def create
	 given_price = contributor_params[:given_price].to_i
  
	 if given_price > 100 
		values = { 
		:business => 'mittal.vitrainee@gmail.com',
		:cmd => '_cart',
		:upload => 1,
		:return => fundfromfriend_url(session[:event_product_id],contributor_params[:given_price]),
		}	
	 	values.merge!({
		  "amount_1" => contributor_params[:given_price],
		  "item_name_1" => 'abcs',
		  "item_number_1" => 1,
		  "quantity_1" => 1
	  })  
   	# For test transactions use this URL
		redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
	 else
		redirect_to event_product_url(session[:event_product_id])
		flash[:alert] = "Contribution price must be greater than 100 Rs."
   end 
  end

  # PATCH/PUT /contributors/1
  # PATCH/PUT /contributors/1.json
  def update
    respond_to do |format|
      if @contributor.update(contributor_params)
        format.html { redirect_to @contributor, notice: 'Contributor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contributor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributors/1
  # DELETE /contributors/1.json
  def destroy
    @contributor.destroy
    respond_to do |format|
      format.html { redirect_to contributors_url }
      format.json { head :no_content }
    end
  end

	def userfund
		@contributor = Contributor.new(given_price: params[:given_price])
    @contributor.user = current_user
    @contributor.event_product_id = session[:event_product_id]
    @user_event = @contributor.get_contribution_id(session[:event_product_id])
    @userId = @contributor.get_user_id(@user_event)
    @contributor.user_contribute_id = @userId
		
		@contributor.given_price = params[:given_price]

		@event_product = EventProduct.find(session[:event_product_id])

		#@contributor.given_price = tmp
	
    #@contributor.event_product_id = event_product

    if @contributor.save
			redirect_to event_event_product_url(@user_event, session[:event_product_id])
    end
	end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contributor
      @contributor = Contributor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contributor_params
      params.require(:contributor).permit(:user_id, :event_product_id, :given_price)
    end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/_contributor.html.erb
<% @total_contribution = 0 %>
<% @result = 0 %>

<% @event_product.contributors.each do |contributor| %>
<p>
   <table>
	<tr>
    	<td><%= contributor.get_user_name(contributor.user_id) %></td>
		<div class ="pull-right"><%= contributor.given_price %></div>	
	 </tr>
    </table>

		<%  contributor.get_total_contribution(@event_product.id).each_pair do |key, value| %> 
		<hr>
	        <% @gain_price = @event_product.price_to_gain %> 	
			<% @total_contribution = value %>
			<% @result = @gain_price - @total_contribution %>
		<% end %>	
</p>
		

<% end %>


			<b style="color:green"><div class ="pull-left">Total Contribution </div> <div class="pull-right"><%= @total_contribution %></div></b><br>
			<% if @result > 0 %>
				<hr><b style="color:red"><div class ="pull-left">Remaining</div> <div class="pull-right"> <%= @result %>  </div> </b> 
			<% else %>
				<hr> &nbsp <b style="color:green"> <div class="pull-right"> Achieved  </div> </b> </div>
			<% end %>
		      

app/views/contributors/_form.html.erb
<%= form_for(@contributor) do |f|  %>
  <% if @contributor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contributor.errors.count, "error") %> prohibited this contributor from being saved:</h2>

      <ul>
      <% @contributor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>--!>

  <!--<div class="field">
    <%= f.label :event_product_id %><br>
    <%= f.number_field :event_product_id %>
  </div>--!>

<div class="control-group">
      <%= f.label :Enter_price_to_contribute, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :given_price, :required => true, :class => 'input-xlarge' %>
      </div>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contributors/create.js.erb
/* Add the new contributor to the contributors list */
$("#contribute").html("<%= escape_javascript(render("contributor")) %>");

/* Reset the comment form */
$("#new_contributor")[0].reset();

app/views/contributors/edit.html.erb
<h1>Editing contributor</h1>

<%= render 'form' %>

<%= link_to 'Show', @contributor %> |
<%= link_to 'Back', contributors_path %>

app/views/contributors/index.html.erb
<h4 style="color:#336699;text-align:center"><b>LIST OF CONTRIBUTORS</b> </h4>
<hr>

<table>
  
<div>
	<h5 style="color:black"><b>Contributors By : &nbsp</b></td></font>
	<%= link_to 'Contribution Given by me', contribution_by_me_path('my'), :style=>'color:#336699' %> &nbsp | &nbsp
	<%= link_to 'Contribution Receive by friend', contribution_by_friend_path('friend'), :style=>'color:#336699' %> &nbsp </h5>
	<hr>
</div>
  <tbody>
    <% total = 0%>
    <% @contributor.each do |contributor| %>
      
		<% contributor.event_product_id %>
		<% @user_product_id = contributor.get_product_id(contributor.event_product_id) %>
		
      
		<% @user_event_id = contributor.get_event_id(contributor.event_product_id) %>


		<div class="row">
			<div class="col-md-3">

		<h5 style="color:black"><b>Event name : </b><%= contributor.get_event_name(@user_event_id)%></h5> <br>
		<!--<b>Wish Product</b> : <%= contributor.get_product_name(@user_product_id) %>-->
		<% @event_product_image =  contributor.get_product_id(contributor.event_product_id) %>
	  <%=image_tag(contributor.get_product_image(@event_product_image), :size => "150x100") %>
		</div>
	
		<div class="col-md-9">
		<h5 style="color:black"><b>Contributor Name : </b> <%= contributor.get_user_name(contributor.user_id) %></h5>
		<h5 style="color:black"><b>Friend Name : </b> <%= contributor.get_user_name(contributor.user_contribute_id) %></h5>
    
		
    <h5 style="color:black"><b>Given price : </b> <%= contributor.given_price %></h5>
		<h5 style="color:black"><b>Posted : </b><%= time_ago_in_words(contributor.created_at) %> ago</h5>
		<br>
		<hr>
			</div>
		
    
     
	
		</div>
     <% end %>	
		
	

  </tbody>

</table>

<br>
<h5 style="color:#336699;text-align:center"><%= will_paginate @contributor, :previous_label => 'Previous', :next_label => 'Next' %></h5>
</div>

app/views/contributors/new.html.erb
<h4 style="color:#336699;text-align:left">NEW CONTRIBUTOR</h4>
<hr>

<%= render 'form' %>

<%= link_to 'Back', event_products_path %>

app/views/contributors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @contributor.user_id %>
</p>

<p>
  <strong>Event product:</strong>
  <%= @contributor.event_product_id %>
</p>

<p>
  <strong>Given price:</strong>
  <%= @contributor.given_price %>
</p>


<%= link_to 'Edit', edit_contributor_path(@contributor) %> |
<%= link_to 'Back', contributors_path %>